language: java

dist: trusty

jdk:
  - openjdk8
  - oraclejdk8

env:
  - NODE_VERSION="9.11.1"

before_install:
  - nvm install $NODE_VERSION

install: true

script:
  - mvn clean install -B -Dgpg.skip=true

notifications:
  email:
    on_success: always
    on_failure: always
